# Generated by Django 2.2.7 on 2019-11-20 13:44

import database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokument', models.FileField(upload_to=database.models.user_dir_path)),
            ],
        ),
        migrations.CreateModel(
            name='Przychodnia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('uica', models.CharField(max_length=100)),
                ('nr_ulicy', models.CharField(max_length=100)),
                ('nr_mieszkania', models.CharField(max_length=100, null=True)),
                ('kod_pocztowy', models.CharField(max_length=100)),
                ('miasto', models.CharField(max_length=100)),
                ('wojewodztwo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, null=True)),
                ('telefon', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='telefon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='nr_mieszkania',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='telefon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wizyty', models.DateTimeField()),
                ('uwagi', models.CharField(max_length=500)),
                ('dokumenty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Dokument')),
                ('fk_id_lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Lekarz')),
                ('fk_id_pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Pacjent')),
                ('fk_id_przychodnia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Przychodnia')),
            ],
        ),
        migrations.AddField(
            model_name='przychodnia',
            name='lekarze',
            field=models.ManyToManyField(to='database.Lekarz'),
        ),
        migrations.AddField(
            model_name='pacjent',
            name='dokumenty',
            field=models.ManyToManyField(null=True, to='database.Dokument'),
        ),
    ]
