# Generated by Django 2.2.7 on 2019-11-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191120_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacjent',
            name='dokumenty',
        ),
        migrations.AddField(
            model_name='pacjent',
            name='dokumenty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Dokument'),
        ),
        migrations.RemoveField(
            model_name='wizyta',
            name='dokumenty',
        ),
        migrations.AddField(
            model_name='wizyta',
            name='dokumenty',
            field=models.ManyToManyField(to='database.Dokument'),
        ),
    ]
