# Generated by Django 3.0 on 2019-12-08 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20191208_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='dokumenty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Dokument'),
        ),
    ]
