# Generated by Django 2.2.7 on 2019-11-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20191120_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Badanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Objawy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='JednostkaChorobowa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=500)),
                ('nr_icd', models.CharField(max_length=100)),
                ('objawy', models.ManyToManyField(to='database.Objawy')),
            ],
        ),
        migrations.CreateModel(
            name='DaneStatystyczne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wojewodztwo', models.CharField(max_length=100)),
                ('liczba_zachorowan', models.BigIntegerField()),
                ('choroba', models.ManyToManyField(to='database.JednostkaChorobowa')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='fk_id_admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Administrator'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='badania',
            field=models.ManyToManyField(to='database.Badanie'),
        ),
        migrations.AddField(
            model_name='wizyta',
            name='objawy',
            field=models.ManyToManyField(to='database.Objawy'),
        ),
    ]
