# Generated by Django 2.2.7 on 2019-11-30 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20191121_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lekarz',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pacjent',
            name='email',
        ),
    ]
