# Generated by Django 3.0 on 2019-12-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20191208_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizyta',
            name='diagnoza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.JednostkaChorobowa'),
        ),
    ]
