# Generated by Django 3.0 on 2019-12-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_wizyta_diagnoza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danestatystyczne',
            old_name='liczba_zachorowan',
            new_name='liczba_ludnosci',
        ),
        migrations.RemoveField(
            model_name='danestatystyczne',
            name='choroba',
        ),
        migrations.CreateModel(
            name='DaneEpidemiologiczne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liczba_zachorowan', models.BigIntegerField()),
                ('prewalencja', models.CharField(blank=True, max_length=50, null=True)),
                ('dane_statystyczne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.DaneStatystyczne')),
                ('jednostka_chorobowa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.JednostkaChorobowa')),
            ],
            options={
                'ordering': ('dane_statystyczne__wojewodztwo',),
            },
        ),
    ]
