# Generated by Django 2.2.7 on 2019-11-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20191130_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='kod_pocztowy',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='miasto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='nr_ulicy',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='pesel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='ulica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pacjent',
            name='wojewodztwo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
