# Generated by Django 3.0 on 2019-12-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_daneepidemiologiczne_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daneepidemiologiczne',
            options={'ordering': ('data',)},
        ),
    ]
