# Generated by Django 2.2.7 on 2019-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20191130_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lekarz',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
