# Generated by Django 3.0 on 2019-12-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20191227_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daneepidemiologiczne',
            options={'ordering': ('data', 'dane_statystyczne__wojewodztwo', 'jednostka_chorobowa__nazwa')},
        ),
    ]
