# Generated by Django 2.2.7 on 2019-12-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20191201_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacjent',
            name='wojewodztwo',
            field=models.CharField(choices=[('BRAK', 'Brak'), ('DOLNOSLAKIE', 'Dolnośląskie'), ('KUJAWSKOPOMORSKIE', 'Kujawsko-pomorskie'), ('LUBELSKIE', 'Lubelskie'), ('LUBUSKIE', 'Lubuskie'), ('LODZKIE', 'Łódzkie'), ('MALOPOLSKIE', 'Małopolskie'), ('MAZOWIECKIE', 'Mazowieckie'), ('OPOLSKIE', 'Opolskie'), ('PODKARPACKIE', 'Podkarpackie'), ('PODLASKIE', 'Podlaskie'), ('POMORSKIE', 'Pomorskie'), ('SLASKIE', 'Śląskie'), ('SWIETOKRZYSKIE', 'Świętokrzyskie'), ('WARMINSKOMAZURSKIE', 'Warmińsko-mazurskie'), ('WIELKOPOLSKIE', 'Wielkopolskie'), ('ZACHODNIOPOMORSKIE', 'Zachodniopomorskie')], default='BRAK', max_length=30),
        ),
        migrations.AlterField(
            model_name='przychodnia',
            name='wojewodztwo',
            field=models.CharField(choices=[('BRAK', 'Brak'), ('DOLNOSLAKIE', 'Dolnośląskie'), ('KUJAWSKOPOMORSKIE', 'Kujawsko-pomorskie'), ('LUBELSKIE', 'Lubelskie'), ('LUBUSKIE', 'Lubuskie'), ('LODZKIE', 'Łódzkie'), ('MALOPOLSKIE', 'Małopolskie'), ('MAZOWIECKIE', 'Mazowieckie'), ('OPOLSKIE', 'Opolskie'), ('PODKARPACKIE', 'Podkarpackie'), ('PODLASKIE', 'Podlaskie'), ('POMORSKIE', 'Pomorskie'), ('SLASKIE', 'Śląskie'), ('SWIETOKRZYSKIE', 'Świętokrzyskie'), ('WARMINSKOMAZURSKIE', 'Warmińsko-mazurskie'), ('WIELKOPOLSKIE', 'Wielkopolskie'), ('ZACHODNIOPOMORSKIE', 'Zachodniopomorskie')], default='BRAK', max_length=30),
        ),
    ]
