# Generated by Django 3.0 on 2020-01-02 13:21

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200102_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='dokument',
            field=models.FileField(upload_to=database.models.user_dir_path),
        ),
    ]
