# Generated by Django 2.2.7 on 2019-12-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20191201_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='przychodnia',
            name='uica',
        ),
        migrations.AddField(
            model_name='przychodnia',
            name='ulica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='przychodnia',
            name='kod_pocztowy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='przychodnia',
            name='miasto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='przychodnia',
            name='nazwa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='przychodnia',
            name='nr_ulicy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
