# Generated by Django 3.0 on 2020-01-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200102_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokument',
            name='dokument',
            field=models.FileField(upload_to=''),
        ),
    ]
