# Generated by Django 3.0 on 2019-12-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20191202_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.CharField(default='BRAK', max_length=100, null=True),
        ),
    ]
