# Generated by Django 3.0 on 2020-01-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200102_1447'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wizyta',
            name='Unikatowosc wizyty',
        ),
        migrations.AddConstraint(
            model_name='wizyta',
            constraint=models.UniqueConstraint(fields=('data_wizyty', 'fk_id_lekarz'), name='Unikatowosc wizyty'),
        ),
    ]
