# Generated by Django 3.0 on 2019-12-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20191207_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lekarz',
            options={'ordering': ('id',)},
        ),
    ]
