# Generated by Django 3.0 on 2019-12-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20191207_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='badania',
            field=models.ManyToManyField(blank=True, to='database.Badanie'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='dokumenty',
            field=models.ManyToManyField(blank=True, to='database.Dokument'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='objawy',
            field=models.ManyToManyField(blank=True, to='database.Objawy'),
        ),
    ]
