# Generated by Django 3.0 on 2019-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20191207_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizyta',
            name='badania',
            field=models.ManyToManyField(null=True, to='database.Badanie'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='dokumenty',
            field=models.ManyToManyField(null=True, to='database.Dokument'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='objawy',
            field=models.ManyToManyField(null=True, to='database.Objawy'),
        ),
        migrations.AlterField(
            model_name='wizyta',
            name='uwagi',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
