# Generated by Django 3.0 on 2019-12-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20191207_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizyta',
            options={'ordering': ('id',)},
        ),
    ]
