# Generated by Django 3.0 on 2019-12-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20191208_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danestatystyczne',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='jednostkachorobowa',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='objawy',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='przychodnia',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='jednostkachorobowa',
            name='nazwa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='danestatystyczne',
            name='choroba',
        ),
        migrations.AddField(
            model_name='danestatystyczne',
            name='choroba',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.JednostkaChorobowa'),
        ),
        migrations.AlterField(
            model_name='danestatystyczne',
            name='wojewodztwo',
            field=models.CharField(choices=[('BRAK', 'Brak'), ('DOLNOSLAKIE', 'Dolnośląskie'), ('KUJAWSKOPOMORSKIE', 'Kujawsko-pomorskie'), ('LUBELSKIE', 'Lubelskie'), ('LUBUSKIE', 'Lubuskie'), ('LODZKIE', 'Łódzkie'), ('MALOPOLSKIE', 'Małopolskie'), ('MAZOWIECKIE', 'Mazowieckie'), ('OPOLSKIE', 'Opolskie'), ('PODKARPACKIE', 'Podkarpackie'), ('PODLASKIE', 'Podlaskie'), ('POMORSKIE', 'Pomorskie'), ('SLASKIE', 'Śląskie'), ('SWIETOKRZYSKIE', 'Świętokrzyskie'), ('WARMINSKOMAZURSKIE', 'Warmińsko-mazurskie'), ('WIELKOPOLSKIE', 'Wielkopolskie'), ('ZACHODNIOPOMORSKIE', 'Zachodniopomorskie')], default='BRAK', max_length=100),
        ),
    ]
