# Generated by Django 3.0 on 2019-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20191208_1142'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wizyta',
            constraint=models.UniqueConstraint(fields=('data_wizyty', 'fk_id_lekarz', 'fk_id_pacjent'), name='Unikatowosc wizyty'),
        ),
    ]
